### ISSUE TITLE
Multilingual support

### ISSUE THREAD

**Issue by Benoit9** [JuliaNeuralGraphics/Whisper.jl#1]
Nice work! What is needed to support multilingual model? I might give it a try.

**Comment by pxl-th** [comment]
Hi! If I recall correctly, we just need support for multilingual tokenizer.
You can look at how original multilingual tokenizer [works](https://github.com/openai/whisper/blob/ba3f3cd54b0e5b8ce1ab3de13e32122d0d5f98ab/whisper/tokenizer.py#L382) and how it is [used](https://github.com/openai/whisper/blob/ba3f3cd54b0e5b8ce1ab3de13e32122d0d5f98ab/whisper/decoding.py#L519) then.

I think once encoding/decoding works for multiple languages it should be enough to just load the respective model.

**Comment by Benoit9** [comment]
Thanks!
Indeed, there wasn't much to do. Only handle the last token of the multilingual token vocab, which the Base64 didn't like.
I also added support for the new large-v3 model.
#2

**Comment by Benoit9** [comment]
Digging a little more, I realize that having the token vocab one longer does shift the token IDs of all the special tokens that come after. For example <|startoftranscript|> will have id 50258 in "tiny", but 50257 in "tiny.en". Looking at the config.json file on huggingface (https://huggingface.co/openai/whisper-tiny/blob/main/config.json), 50258 seems correct. It does not seem to change anything to the transcriptions though...
